### ISSUE TITLE
No CUDA toolkit detected on this system

### ISSUE THREAD

**Issue by lixiangchun** [razorx89/nmfgpu4R#3]
After installed nmfgpu to /usr/local/nmfgpu, I can run `nmfgpu_example` successfully. However, when calling `nmfgpu4R.init()`, error occurred - `Error in nmfgpu4R.init() : No CUDA toolkit detected on this system`. I already set `NMFGPU_ROOT=/usr/local/nmfgpu`. My CUDA is version 9.1.

**Comment by razorx89** [comment]
Did you configure an environment variable named CUDA_ROOT pointing to your CUDA installation?

**Comment by lixiangchun** [comment]
@razorx89 Thanks. It works perfectly right now when added `export CUDA_ROOT=/usr/local/cuda-9.1/` and `export NMFGPU_ROOT=/usr/local/nmfgpu/` to my `.bashrc`.
